export const templates = {
    "business-email": {
        name: "Business Email",
        text: "Dear [Name],\n\nI hope this email finds you well. I am writing to follow up on our recent conversation regarding the upcoming project collaboration. We are excited about the opportunity to work together and believe this partnership will yield excellent results.\n\nAs discussed, we will need to coordinate our teams and establish clear timelines for deliverables. I would appreciate the chance to schedule a meeting next week to discuss the project scope in greater detail.\n\nPlease let me know your availability, and I will send out calendar invitations accordingly. Thank you for your time and consideration.\n\nBest regards,\n[Your Name]"
    },
    "academic-essay": {
        name: "Academic Essay",
        text: "The Impact of Technology on Modern Education\n\nIn the twenty-first century, technology has fundamentally transformed the landscape of education. From interactive whiteboards to online learning platforms, technological innovations have revolutionized how students learn and how educators teach. This transformation has brought both unprecedented opportunities and significant challenges that educational institutions must navigate carefully.\n\nThe integration of digital tools in classrooms has enhanced student engagement and accessibility. Interactive learning platforms allow students to learn at their own pace, while multimedia resources cater to different learning styles. Furthermore, technology has made education more accessible to students with disabilities and those in remote locations.\n\nHowever, this digital revolution also presents challenges. The digital divide creates inequalities between students who have access to technology and those who do not. Additionally, concerns about screen time and the need for digital literacy skills have become increasingly important considerations for educators and policymakers.\n\nIn conclusion, while technology offers tremendous potential to improve educational outcomes, its implementation must be thoughtful and equitable to ensure all students benefit from these advances."
    },
    "creative-writing": {
        name: "Creative Writing",
        text: "The old lighthouse stood majestically on the rocky cliff, its weathered walls telling stories of countless storms weathered and ships guided safely to shore. Sarah approached the ancient structure with reverence, feeling the weight of history in every step she took across the moss-covered stones.\n\nThe afternoon sun cast long shadows through the lighthouse's broken windows, creating patterns that danced across the worn wooden floors. She could almost hear the echoes of the lighthouse keeper's footsteps, climbing the spiral staircase day after day, tending to the beacon that had served as a guardian angel for sailors navigating treacherous waters.\n\nAs she climbed the narrow stairs, each step creaked beneath her feet, and she wondered about all the people who had made this same journey before her. The view from the top was breathtaking – endless ocean stretching to the horizon, where the sky met the sea in a perfect line of blue.\n\nThis lighthouse had been more than just a navigation aid; it had been a symbol of hope, a beacon of safety in the darkness. Now, though no longer operational, it continued to inspire visitors like Sarah, who came seeking solitude and connection to the maritime heritage of the coast."
    },
    "technical-documentation": {
        name: "Technical Documentation",
        text: "API Authentication Guide\n\n1. Overview\nThis document provides comprehensive instructions for implementing authentication in our REST API. The authentication system uses JWT (JSON Web Tokens) for secure session management and supports both username/password and OAuth2 authentication methods.\n\n2. Prerequisites\n- Valid API credentials\n- HTTPS-enabled environment\n- JSON parsing capabilities\n- Understanding of HTTP headers\n\n3. Authentication Flow\nStep 1: Obtain authentication credentials from the developer portal\nStep 2: Make a POST request to /auth/login with your credentials\nStep 3: Store the returned JWT token securely\nStep 4: Include the token in subsequent API requests using the Authorization header\n\n4. Implementation Example\nconst response = await fetch('/api/auth/login', {\n  method: 'POST',\n  headers: {\n    'Content-Type': 'application/json'\n  },\n  body: JSON.stringify({\n    username: 'your_username',\n    password: 'your_password'\n  })\n});\n\n5. Error Handling\nThe API returns specific error codes for authentication failures:\n- 401: Invalid credentials\n- 403: Access forbidden\n- 429: Rate limit exceeded\n\nImplement appropriate retry logic and user feedback for these scenarios."
    },
    "marketing-copy": {
        name: "Marketing Copy",
        text: "Transform Your Business with Our Revolutionary Software Solution!\n\nAre you tired of juggling multiple tools and losing valuable time on repetitive tasks? Discover the power of our all-in-one business management platform that's designed to streamline your operations and boost productivity by up to 300%.\n\nWhat makes us different?\n✓ Intuitive interface that requires zero training\n✓ Seamless integration with 200+ popular business tools\n✓ Advanced analytics that provide actionable insights\n✓ 24/7 customer support from real humans\n✓ Enterprise-grade security you can trust\n\nJoin over 50,000 satisfied customers who have already transformed their businesses. From small startups to Fortune 500 companies, our solution scales with your needs and grows with your success.\n\nDon't let inefficiency hold your business back. Take action today and experience the difference our software can make. Start your free 30-day trial now – no credit card required, no hidden fees, just pure business transformation waiting to happen.\n\nReady to revolutionize your workflow? Click the button below and join the productivity revolution!"
    }
};
